var app = angular.module('clubsApp', []);

app.controller('clubsController', function($scope){

	$scope.listAllClubs = true;
	$scope.clubs = [
	{
		name : "Art Club",
		description : "Spread interest of art through various activities",
		day : "Friday",
		location : "D-2",
		advisor : "Fenton",
		genre : "Art",
		time : "lunch",	
		contact_name : "Oona Guensche",
		contact_email : "me@gmail.com",
		contact_website : ""
	},
	{
		name : "Black Student Union (BSU)",
		description : "To provide educational and positive promotion of black culture and all minorities and the civil rights",
		day : "Wednesday",
		location : "B-2",
		advisor : "Charuhas",
		genre : "Countries and Culture",
		time : "lunch",	
		contact_name : "Mikai Lewis",
		contact_email : "me@gmail.com",
		contact_website : ""
	},
	{
		name : "Bring Change 2 Mind",
		description : "To promote & educate mental health awareness",
		day : "Wednesday",
		location : "C-6",
		advisor : "Carter",
		genre : "Community Service",
		time : "lunch",	
		contact_name : "Me",
		contact_email : "me@gmail.com",
		contact_website : ""
	},
	{
		name : "C.S.F.",
		description : "Community Service",
		day : "Wednesday",
		location : "J-3",
		advisor : "Lobo",
		genre : "Community Service",
		time : "lunch",	
		contact_name : "Sai/Neel Wignarajah",
		contact_email : "me@gmail.com",
		contact_website : ""
	},
	{
		name : "Chess Club",
		description : "Teach students how to play chess",
		day : "Friday",
		location : "J-9",
		advisor : "Jones",
		genre : "other",
		time : "After school",	
		contact_name : "Andy Li",
		contact_email : "me@gmail.com",
		contact_website : ""
	},
	{
		name : "Chinese Yo-Yo",
		description : "Help students learn yo-yo skills",
		day : "Friday",
		location : "Small gym",
		advisor : "Halliday",
		genre : "Countries and Culture",
		time : "After school",	
		contact_name : "Kai Zamora",
		contact_email : "me@gmail.com",
		contact_website : ""
	},
	{
		name : "Chinese-American Youth Association (C.A.Y.A)",
		description : "Promote awareness of Chinese culture",
		day : "Every other Thursday",
		location : "B-28",
		advisor : "Pastor",
		genre : "Countries and Cultures",
		time : "lunch",	
		contact_name : "Maxus Wong",
		contact_email : "me@gmail.com",
		contact_website : ""
	},
	{
		name : "Computer Science Club",
		description : "Prepare members for real-world coding",
		day : "Monday",
		location : "P-6 or D-27",
		advisor : "Sos",
		genre : "Tech Club",
		time : "lunch",	
		contact_name : "Ahad Rauf",
		contact_email : "me@gmail.com",
		contact_website : ""
	},
	{
		name : "Dungeons and Dragons",
		description : "Allow students to express imaginitive thinking",
		day : "First and Third Fridays",
		location : "D-17",
		advisor : "H. Richey",
		genre : "other",
		time : "lunch",
		contact_name : "Noah Thomas/Jordan Reni",
		contact_email : "",
		contact_website : "",
	},
	{
		name : "Earth Club",
		description : "Go on hikes, do erath related volunteer oppurtunities and community service",
		day : "Thursday",
		location : "D-24",
		advisor : "Bisagno",
		genre : "Service Clubs",
		time : "lunch",
		contact_name : "Dina Parks",
		contact_email : "",
		contact_website : "",
	},
	{
		name : "Engineering Club",
		description : "Get students interested in engineering",
		day : "Friday",
		location : "I-4",
		advisor : "Evans",
		genre : "Academic Clubs",
		time : "lunch",
		contact_name : "Robathan Harries",
		contact_email : "",
		contact_website : "",
	},
	{
		name : "Falcon Friends (Best Buddies)",
		description : "Make sure buddies have a friend",
		day : "Fridays",
		location : "A-10",
		advisor : "Hooven",
		genre : "Service Clubs",
		time : "lunch",
		contact_name : "Tamara Wilson",
		contact_email : "",
		contact_website : "",
	},
	{
		name : "Fellowship of Christian Athletes",
		description : "Promote the blending of sports, faith and education",
		day : "2 Thursday's a month",
		location : "P-2",
		advisor : "Scavone",
		genre : "Athletics",
		time : "lunch",
		contact_name : "Tessie Scavone",
		contact_email : "",
		contact_website : "",
	},
	{
		name : "F.I.S.H",
		description : "Reach students with gospel and create disciples",
		day : "Friday",
		location : "J-1",
		advisor : "Sears",
		genre : "Countries and Culture",
		time : "lunch",
		contact_name : "Jennifer Kim",
		contact_email : "",
		contact_website : "",
	},
	{
		name : "Free the Children",
		description : "Help against child labor through Free the Children events and fundraising, charities ad spreading awareness",
		day : "Wednesday",
		location : "B-29",
		advisor : "Williams",
		genre : "Service Clubs",
		time : "lunch",
		contact_name : "Connie Hsu",
		contact_email : "",
		contact_website : "",
	},
	{
		name : "French Club",
		description : "Promote French culture and language on campus",
		day : "Every other Thursday",
		location : "B-31",
		advisor : "Porfolio",
		genre : "Academic Clubs",
		time : "lunch",
		contact_name : "Lucas DeBernardi",
		contact_email : "",
		contact_website : "",
	},
	{
		name : "French Honor Society",
		description : "Honor students of French for their higher academic acheivement",
		day : "Every other Thursday",
		location : "B-31",
		advisor : "Porfolio",
		genre : "Academic Clubs",
		time : "lunch",
		contact_name : "Sophie Nguyen",
		contact_email : "",
		contact_website : "",
	},
	{
		name : "Future Business Leaders of America (FBLA)",
		description : "Bring business and education together though leadership and career development programs",
		day : "Thursday",
		location : "I-1",
		advisor : "Z. Lipman",
		genre : "Academic Clubs",
		time : "lunch",
		contact_name : "Rohan Krishnakumar",
		contact_email : "",
		contact_website : "",
	},
	];
	$scope.goToClub= function(club){
		$scope.listAllClubs= false;
		$scope.focusClub= club;
	}
}
);